version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm install

  pre_build:
    commands:
      - echo "API_BASE_URL=$API_BASE_URL" >> .env
      - echo "WS_URL=$WS_URL" >> .env
      - echo "NODE_ENV=production" >> .env

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync .output/public/ s3://$S3_BUCKET_NAME/ --delete

artifacts:
  files:
    - .output/**/*
  base-directory: .output